kiocopy: more logging and user info

diff --git a/kiocopy b/kiocopy
--- a/kiocopy
+++ b/kiocopy
@@ -43,7 +43,8 @@ echo "Warning: This tries to create GB worth of files in /tmp."
 echo "This is meant to try to assist with possibly replicating https://bugs.kde.org/show_bug.cgi?id=162211"
 echo "Warning: This script when running without a seed file, generates many \$RANDOM numbers, which might use up entropy"
 echo "You can specify a seed file as an argument to build a previously created copy source tree"
-echo "It requires root access to mount and unmount the test loopback file systems it creates"
+echo "It requires sudo access to mount and unmount the test loopback file systems it creates"
+echo "This script runs kioclient as a user, but will prompt for sudo access to do things like mount and unmount the loopback filesystems."
 echo ""
 echo "Press Enter..."
 read a
@@ -341,6 +342,10 @@ do
       echo "Would have created folder $ItemPath"
     else
       mkdir -p "$ItemPath"
+      if [[ $? != 0 ]]
+      then
+        echo "Failed to create folder $ItemPath" >> /tmp/kiocopy/$DateStamp/logs/self.log
+      fi
     fi
   elif [[ $ItemSize == 0 ]]
   then
@@ -349,6 +354,10 @@ do
       echo "Would have created empty file $ItemPath"
     else
       touch "$ItemPath"
+      if [[ $? != 0 ]]
+      then
+        echo "Failed to empty file $ItemPath" >> /tmp/kiocopy/$DateStamp/logs/self.log
+      fi
     fi
   else
     if [[ $DoDryRun == 1 ]]
@@ -356,6 +365,10 @@ do
       echo "Would have created $ItemSize byte file $ItemPath"
     else
       fallocate -l $ItemSize "$ItemPath"
+      if [[ $? != 0 ]]
+      then
+        echo "Failed to $ItemSize byte file $ItemPath" >> /tmp/kiocopy/$DateStamp/logs/self.log
+      fi
     fi
   fi
 done
